spring:
  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://db:3306/turtle-neck-savior-dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
