spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://db:3306/turtle-neck-savior-dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:h2:mem:turtle-neck-savior-dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


  output:
    ansi:
      enabled: always

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

logging:
  level:
    org.hibernate.type: trace

